force-app/main/default/objects/Oportunity_Revenue_Range__mdt/Oportunity_Revenue_Range__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for defining the opportunity colors according to their revenue ranges</description>
    <label>Oportunity Revenue Range</label>
    <pluralLabel>Oportunity Revenue Ranges</pluralLabel>
</CustomObject>

force-app/main/default/objects/Oportunity_Revenue_Range__mdt/fields/Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Lower_Limit__c</fullName>
    <description>Lower limit for the opportunities revenue ranges</description>
    <label>Lower Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunity_Revenue_Range__mdt/fields/Upper_Limit__c.field-meta.xml
<CustomField>
    <fullName>Upper_Limit__c</fullName>
    <description>Upper limit for the opportunities revenue range</description>
    <label>Upper Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Opportunity priority according to it&apos;s revenue range</description>
    <label>Priority</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityHelperTest.cls
@isTest
private class OpportunityHelperTest {

    @TestSetup
    static void makeData(){
        insert DataFactory.createAccounts(4);
    }

    @isTest
    static void testGreenOpportunityUpdate(){
		Oportunity_Revenue_Range__mdt range = Oportunity_Revenue_Range__mdt.getInstance('Green');
        
        Account acct = [
            SELECT Id, AnnualRevenue 
            FROM Account
			WHERE AnnualRevenue >= :range.Lower_Limit__c
        ];
           
        Opportunity opp = DataFactory.createOpportunities(1, new Account[]{acct})[0];
		insert opp;
        
        Opportunity insertedOpp = [SELECT Priority__c FROM Opportunity WHERE Id=:opp.Id];
        
        System.assertEquals('Green', insertedOpp.Priority__c);
    }

    @isTest
    static void testYellowOpportunityUpdate(){
        Oportunity_Revenue_Range__mdt range = Oportunity_Revenue_Range__mdt.getInstance('Yellow');
        
        Account acct = [
            SELECT Id, AnnualRevenue 
            FROM Account
			WHERE AnnualRevenue <= :range.Upper_Limit__c AND AnnualRevenue >= :range.Lower_Limit__c 
        ];
           
        Opportunity opp = DataFactory.createOpportunities(1, new Account[]{acct})[0];
		insert opp;
        
        Opportunity insertedOpp = [SELECT Priority__c FROM Opportunity WHERE Id=:opp.Id];
        
        System.assertEquals('Yellow', insertedOpp.Priority__c);
    }

    @isTest
    static void testRedOpportunityUpdate(){
        Oportunity_Revenue_Range__mdt range = Oportunity_Revenue_Range__mdt.getInstance('Red');
        
        Account acct = [
            SELECT Id, AnnualRevenue 
            FROM Account
			WHERE AnnualRevenue <= :range.Upper_Limit__c AND AnnualRevenue >= :range.Lower_Limit__c 
        ];
           
        Opportunity opp = DataFactory.createOpportunities(1, new Account[]{acct})[0];
		insert opp;
        
        Opportunity insertedOpp = [SELECT Priority__c FROM Opportunity WHERE Id=:opp.Id];
        
        System.assertEquals('Red', insertedOpp.Priority__c);
    }
    
    @isTest
    static void testOrangeOpportunityUpdate(){
        Oportunity_Revenue_Range__mdt range = Oportunity_Revenue_Range__mdt.getInstance('Orange');
        
        Account acct = [
            SELECT Id, AnnualRevenue 
            FROM Account
			WHERE AnnualRevenue = null
        ];
           
        Opportunity opp = DataFactory.createOpportunities(1, new Account[]{acct})[0];
		insert opp;
        
        Opportunity insertedOpp = [SELECT Priority__c FROM Opportunity WHERE Id=:opp.Id];
        
        System.assertEquals('Orange', insertedOpp.Priority__c);
    }

}