force-app/main/default/objects/Oportunity_Revenue_Range__mdt/Oportunity_Revenue_Range__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for defining the opportunity colors according to their revenue ranges</description>
    <label>Oportunity Revenue Range</label>
    <pluralLabel>Oportunity Revenue Ranges</pluralLabel>
</CustomObject>

force-app/main/default/objects/Oportunity_Revenue_Range__mdt/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Oportunity_Revenue_Range__mdt/fields/Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Lower_Limit__c</fullName>
    <description>Lower limit for the opportunities revenue ranges</description>
    <label>Lower Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Opportunity priority according to it&apos;s revenue range</description>
    <label>Priority</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountHelperTest.cls
@isTest
private class AccountHelperTest {

    @testSetup
    static void makeDate(){
        DataFactory.createData(4);
    }
    
    @isTest
    static void checkOppCreation(){
        Opportunity[] opps = [
          SELECT Id
          FROM Opportunity 
        ];
        
        Integer beforeInsertOpps = opps.size();
        
        Account acct = new Account(Name='TestAccountForOpp');
        insert acct;
        
        opps = [
          SELECT Id
          FROM Opportunity 
        ];
        
        System.assertEquals(beforeInsertOpps+1,opps.size());
    }
    
    
    @isTest
    static void testOppUpdateOnAnnualRevChange(){
		Oportunity_Revenue_Range__mdt range = Oportunity_Revenue_Range__mdt.getInstance('Green');
        
        Account acctOrange = [
            SELECT Id, AnnualRevenue 
            FROM Account
			WHERE AnnualRevenue = null
        ];
        
        acctOrange.AnnualRevenue = range.Lower_Limit__c + 1;
        update acctOrange;
                
        Opportunity opp = [
            SELECT Priority__c
            FROM Opportunity
            WHERE AccountId=:acctOrange.Id
            LIMIT 1
        ];
        
        System.assertEquals(range.Color__c, opp.Priority__c);
    }
    
}