force-app/main/default/objects/Oportunity_Revenue_Range__mdt/Oportunity_Revenue_Range__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for defining the opportunity colors according to their revenue ranges</description>
    <label>Oportunity Revenue Range</label>
    <pluralLabel>Oportunity Revenue Ranges</pluralLabel>
</CustomObject>

force-app/main/default/objects/Oportunity_Revenue_Range__mdt/fields/Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Lower_Limit__c</fullName>
    <description>Lower limit for the opportunities revenue ranges</description>
    <label>Lower Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunity_Revenue_Range__mdt/fields/Upper_Limit__c.field-meta.xml
<CustomField>
    <fullName>Upper_Limit__c</fullName>
    <description>Upper limit for the opportunities revenue range</description>
    <label>Upper Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Opportunity priority according to it&apos;s revenue range</description>
    <label>Priority</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityHelper.cls
public with sharing class OpportunityHelper {
    
    public void assignOppPriority(Opportunity opp){
		List<Oportunity_Revenue_Range__mdt> ranges = Oportunity_Revenue_Range__mdt.getAll().values();
		
        for (Oportunity_Revenue_Range__mdt range : ranges) {
            if (range.Label == 'Green' && opp.Account.AnnualRevenue >= range.Lower_Limit__c){
                    opp.Priority__c = range.MasterLabel;
            } else if (range.Label == 'Orange' && opp.Account.AnnualRevenue == null){
                    opp.Priority__c = range.MasterLabel;
            } else if (opp.Account.AnnualRevenue >= range.Lower_Limit__c && opp.Account.AnnualRevenue <= range.Upper_Limit__c) {
                opp.Priority__c = range.MasterLabel;
            }
		}
    }
    
    public void insertOpportunitiesPriorities(list<Opportunity> opps){ 
        Id[] acctsIds = new Id[]{};
        for(Opportunity opp: opps){
            if (opp.AccountId != null){
            	acctsIds.add(opp.AccountId);    
            }
        }
        
       	Map<Id, Account> accts = new Map<Id, Account>([
            SELECT Id, AnnualRevenue
            FROM Account
            WHERE Id IN :acctsIds
        ]);
                
        for (Opportunity opp: opps){
            opp.Account = accts.get(opp.AccountId);
            assignOppPriority(opp);
        }
    }
    
    public void updateOpportunitiesPriorities(list<Opportunity> opps){        
        for (Opportunity opp: opps){
            assignOppPriority(opp);
        }
    }
}