force-app/main/default/objects/Oportunity_Revenue_Range__mdt/Oportunity_Revenue_Range__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for defining the opportunity colors according to their revenue ranges</description>
    <label>Oportunity Revenue Range</label>
    <pluralLabel>Oportunity Revenue Ranges</pluralLabel>
</CustomObject>

force-app/main/default/objects/Oportunity_Revenue_Range__mdt/fields/Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Lower_Limit__c</fullName>
    <description>Lower limit for the opportunities revenue ranges</description>
    <label>Lower Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DataFactory.cls
public class DataFactory {
    public static Opportunity[] createOpportunities(integer size, Account[] accts){
        Date d = Date.newInstance(2023, 1, 1);        
        Opportunity[] opps = new Opportunity[]{};
        for (integer i = 0; i < size; i++){
            opps.add(
                new Opportunity(Name='TestOpp'+i,StageName='Closed Won', CloseDate=d, AccountId=accts.get(i).Id)
            );
        }
        return opps;
    }
    
    public static Account[] createAccounts(integer size){
        Account[] accts = new Account[]{};
		List<Oportunity_Revenue_Range__mdt> ranges = Oportunity_Revenue_Range__mdt.getAll().values();
        for (integer i = 0; i < size; i++){
            Oportunity_Revenue_Range__mdt range = ranges.get(math.mod(i, ranges.size()));
            if(range.Label == 'Orange'){
				accts.add(new Account(Name='TestAcct'+i));
            }else {
				accts.add(new Account(Name='TestAcct'+i, AnnualRevenue=range.Lower_Limit__c+1));
            }
            
        }
        return accts;
    }
    
    public static void createData(integer size){
		Account[] accts = createAccounts(size);
        insert accts;
        Opportunity[] opps = createOpportunities(size, accts);
        insert opps;
    }
    
}